language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - git checkout package-lock.json
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: >-
        FGC4cfcd62eFsXRUmI/She0TY/rbiwtLaZb6lsFpQ1TC/P1yKMgVTL6PIeE4T/eMijDlAbCdtMMNIbj5vOSzUsdHbB0OHJghY7JQ27JdnRKQRUxPErLG35Md118qF7aG55f6mfeZaVYCMFQFWyZzFrbQ5JG1TDJ8rSkxxpOW0L4=
    - secure: >-
        s+J9ZqHKwkwcELs+e+VaTsHFY3V5o8OFVqDZ+3dpxFus3mVmOeQvgqumF+SJ69iKut1VUrUU4UYENZZk/IbE3K3mreYYD7OjQqozwQpEdUsfQ6R6wD1HfyDEcoKHfMJqJyusgD27vmtaz30cdFxGaX1Y/GjtyJCCKo1ZnlG51Ek=
node_js: node
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test --module-resolution=node --npm
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm -s 'default'; fi
dist: trusty
cache:
  directories:
    - node_modules
